apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-udacity
  region: us-east-1

iam:
  withOIDC: true

nodeGroups:
  - name: capstone-udacity-node
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3